package View;

import DAO.UsuarioDAO;
import Mode.Produtos;
import Mode.Usuarios;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FCadastrarUsuario extends javax.swing.JFrame {

    private ArrayList<Produtos> listaProdutos;
    private final UsuarioDAO usuarioDAO;
    private DefaultTableModel modelo;

    public FCadastrarUsuario() throws SQLException {
        initComponents();
        usuarioDAO = new UsuarioDAO();
        initializeTable();
        checkAdminPermissions();
    }

    private void initializeTable() {
        modelo = new DefaultTableModel();
        jTUsuario.setModel(modelo);
        String[] colunas = {"Usuário", "Senha", "Tipo", "Ativado"};
        modelo.setColumnIdentifiers(colunas);

        try {
            for (Usuarios usuario : usuarioDAO.listaUsuarios()) {
                Object[] linha = {usuario.getUsuario(), usuario.getSenha(), usuario.getTipo(), usuario.isAtivado()};
                modelo.addRow(linha);
            }
        } catch (SQLException e) {
            System.err.println("Erro ao carregar Usuários do banco de dados: " + e.getMessage());
        }
    }

    private void checkAdminPermissions() {
        // Aqui você pode simular a lógica para verificar se o usuário logado é administrador
        // Por exemplo:
        String loggedInUserType = "administrador"; // Aqui simulei o tipo de usuário logado

        boolean isAdmin = "administrador".equalsIgnoreCase(loggedInUserType);

        btnAdicionar.setEnabled(isAdmin);
        btnDeletar.setEnabled(isAdmin);
        btnAlterar.setEnabled(isAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnMenu = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        NunesBar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAtivado = new javax.swing.JRadioButton();
        btnDesativado = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        boxCategoria = new javax.swing.JComboBox<>();
        btnAdicionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuario = new javax.swing.JTable();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnMenu.setBackground(new java.awt.Color(255, 153, 0));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMenu.setText("MENU");
        btnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(20, 10, 120, 40);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Logo.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(290, 0, 320, 220);

        NunesBar.setFont(new java.awt.Font("Lucida Bright", 1, 48)); // NOI18N
        NunesBar.setForeground(new java.awt.Color(255, 255, 0));
        NunesBar.setText("NUNES BAR");
        getContentPane().add(NunesBar);
        NunesBar.setBounds(30, 60, 300, 70);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 190, 120, 40);

        buttonGroup1.add(btnAtivado);
        btnAtivado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtivado.setForeground(new java.awt.Color(255, 255, 255));
        btnAtivado.setText("Ativado");
        getContentPane().add(btnAtivado);
        btnAtivado.setBounds(730, 170, 76, 24);

        buttonGroup1.add(btnDesativado);
        btnDesativado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDesativado.setForeground(new java.awt.Color(255, 255, 255));
        btnDesativado.setText("Desativado");
        getContentPane().add(btnDesativado);
        btnDesativado.setBounds(730, 200, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Usuário:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 120, 40);

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(30, 200, 250, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Senha:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 250, 80, 40);
        getContentPane().add(txtPass);
        txtPass.setBounds(110, 250, 170, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Tipo de Usuário:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 200, 200, 40);

        boxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Usuário", "Administrador", "Gerente", "Vendedor" }));
        getContentPane().add(boxCategoria);
        boxCategoria.setBounds(300, 250, 210, 40);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar);
        btnAdicionar.setBounds(520, 250, 100, 40);

        btnDeletar.setText("Deletar");
        btnDeletar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(630, 250, 100, 40);

        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(740, 250, 100, 40);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Usuário Cadastrados");

        jTUsuario.setBackground(new java.awt.Color(102, 102, 102));
        jTUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jTUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTUsuario.setAlignmentX(2.0F);
        jTUsuario.setAlignmentY(2.0F);
        jTUsuario.setRowHeight(50);
        jScrollPane1.setViewportView(jTUsuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 310, 840, 430);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.900x749.jpg"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 900, 749);

        setSize(new java.awt.Dimension(916, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Método para verificar se o usuário logado é administrador


    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String usuario = txtUsuario.getText();
        String senha = new String(txtPass.getPassword());
        String tipo = boxCategoria.getSelectedItem().toString();
        boolean ativado = btnAtivado.isSelected();

        try {
            Usuarios novoUsuario = new Usuarios(usuario, senha, tipo, ativado);
            usuarioDAO.adicionarUsuario(novoUsuario);

            JOptionPane.showMessageDialog(this, "Usuário adicionado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            limparCampos();
            atualizarTabela();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao adicionar usuário: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int linhaSelecionada = jTUsuario.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int idUsuario = (int) modelo.getValueAt(linhaSelecionada, 0); // Obtém o ID do usuário da linha selecionada

            try {
                usuarioDAO.excluirUsuario(idUsuario); // Exclui o usuário pelo ID

                JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                atualizarTabela();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir usuário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um usuário para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int selectedRow = jTUsuario.getSelectedRow();
        if (selectedRow != -1) {
            // Obtém os novos dados do usuário dos campos de entrada
            String usuario = txtUsuario.getText();
            String senha = new String(txtPass.getPassword());
            String tipo = boxCategoria.getSelectedItem().toString();
            boolean ativado = btnAtivado.isSelected();

            try {
                // Obtém o usuário selecionado da tabela
                Usuarios usuarioSelecionado = usuarioDAO.listaUsuarios().get(selectedRow);

                // Atualiza os dados do usuário selecionado
                usuarioSelecionado.setUsuario(usuario);
                usuarioSelecionado.setSenha(senha);
                usuarioSelecionado.setTipo(tipo);
                usuarioSelecionado.setAtivado(ativado);

                // Chama o método para atualizar o usuário no banco de dados
                usuarioDAO.atualizarUsuario(usuarioSelecionado);

                // Exibe uma mensagem de sucesso
                JOptionPane.showMessageDialog(this, "Usuário alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                // Atualiza a tabela após alterar o usuário
                atualizarTabela();

            } catch (SQLException ex) {
                // Exibe uma mensagem de erro em caso de falha
                JOptionPane.showMessageDialog(this, "Erro ao atualizar usuário: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuário para alterar.");
        }

        // Limpa os campos após a operação
        limparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void limparCampos() {
        txtUsuario.setText("");
        txtPass.setText("");
        boxCategoria.setSelectedIndex(0);
        btnAtivado.setSelected(false);
        btnDesativado.setSelected(false);
    }

    private void atualizarTabela() {
        modelo.setRowCount(0); // Limpa a tabela
        try {
            for (Usuarios usuario : usuarioDAO.listaUsuarios()) {
                Object[] linha = {usuario.getUsuario(), usuario.getSenha(), usuario.getTipo(), usuario.isAtivado()};
                modelo.addRow(linha);
            }
        } catch (SQLException e) {
            System.err.println("Erro ao carregar Usuários do banco de dados: " + e.getMessage());
        }
    }

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        FMenu menu = new FMenu(listaProdutos); // Cria uma instância de FMenu passando a lista de produtos
        this.dispose();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FCadastrarUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FCadastrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NunesBar;
    private javax.swing.JComboBox<String> boxCategoria;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JRadioButton btnAtivado;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JRadioButton btnDesativado;
    private javax.swing.JButton btnMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTUsuario;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
