package View;

import DAO.ProdutoDAO;
import Mode.Produtos;
import java.util.ArrayList;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FMenu extends javax.swing.JFrame {

    private ArrayList<Produtos> listaProdutos;

    public FMenu(ArrayList<Produtos> listaProdutos) {
        initComponents();
        this.listaProdutos = listaProdutos; // Inicializa a lista de produtos com o valor fornecido
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelatorio = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCU = new javax.swing.JButton();
        btnCP = new javax.swing.JButton();
        btnCx = new javax.swing.JButton();
        NunesBar = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnRelatorio.setBackground(new java.awt.Color(51, 255, 0));
        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio);
        btnRelatorio.setBounds(390, 400, 150, 93);

        btnSair.setBackground(new java.awt.Color(255, 153, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(20, 10, 120, 40);

        btnCU.setBackground(new java.awt.Color(51, 255, 0));
        btnCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCU.setText("Cadastrar Usuário");
        btnCU.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        btnCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUActionPerformed(evt);
            }
        });
        getContentPane().add(btnCU);
        btnCU.setBounds(480, 300, 150, 93);

        btnCP.setBackground(new java.awt.Color(0, 255, 0));
        btnCP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCP.setText("Cadastrar Produto");
        btnCP.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        btnCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPActionPerformed(evt);
            }
        });
        getContentPane().add(btnCP);
        btnCP.setBounds(290, 300, 160, 93);

        btnCx.setBackground(new java.awt.Color(255, 255, 0));
        btnCx.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btnCx.setText("CAIXA");
        btnCx.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(0, 0, 0)));
        btnCx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCxActionPerformed(evt);
            }
        });
        getContentPane().add(btnCx);
        btnCx.setBounds(290, 510, 350, 93);

        NunesBar.setFont(new java.awt.Font("Lucida Bright", 1, 48)); // NOI18N
        NunesBar.setForeground(new java.awt.Color(255, 255, 0));
        NunesBar.setText("NUNES BAR");
        getContentPane().add(NunesBar);
        NunesBar.setBounds(20, 160, 300, 70);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Logo.png"))); // NOI18N
        getContentPane().add(Logo);
        Logo.setBounds(280, 10, 320, 220);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo.900x749.jpg"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 900, 749);

        setSize(new java.awt.Dimension(916, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setListaProdutos(ArrayList<Produtos> listaProdutos) {
        this.listaProdutos = listaProdutos;
    }

    private void btnCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPActionPerformed
        FCadastrarProduto fcp = new FCadastrarProduto();
        this.dispose();
        fcp.setLocationRelativeTo(null);
        fcp.setVisible(true);
    }//GEN-LAST:event_btnCPActionPerformed

    private void btnCxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCxActionPerformed
        FCaixa cx = new FCaixa(); // Passa a lista de produtos para o construtor de FCaixa
        this.dispose();
        cx.setLocationRelativeTo(null);
        cx.setVisible(true);
    }//GEN-LAST:event_btnCxActionPerformed

    private void btnCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUActionPerformed
        FCadastrarUsuario fcu = null;
        try {
            fcu = new FCadastrarUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(FMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        fcu.setLocationRelativeTo(null);
        fcu.setVisible(true); // Exibe a tela FCadastrarUsuario


    }//GEN-LAST:event_btnCUActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        FLogin login = new FLogin();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        FRelatorio relatorio = new FRelatorio();
        this.dispose();
        relatorio.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ArrayList<Produtos> listaProdutos = new ArrayList<>();
        ProdutoDAO produtoDAO = new ProdutoDAO();

        try {
            listaProdutos.addAll(produtoDAO.listarProdutos()); // Carrega a lista de produtos do banco de dados
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar produtos: " + e.getMessage());
            return; // Encerra a execução se ocorrer um erro ao carregar os produtos
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu(listaProdutos).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NunesBar;
    private javax.swing.JButton btnCP;
    private javax.swing.JButton btnCU;
    private javax.swing.JButton btnCx;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel fundo;
    // End of variables declaration//GEN-END:variables
}
